console.log('Applying V4 - Punchier Headlines Variant');

// Find and update the main headline (h2)
const headline = document.querySelector('.t_heading.t_heading_primary');

// Find and update the subheadline (h3)
const subheadline = document.querySelector('.page-heading_subTitle___1u4b');

if (headline && subheadline) {
  // V4 Copy
  headline.textContent = 'Less \'What If,\' More \'Let\'s Go!\'';
  subheadline.textContent = 'Secure your ride against accidents, theft, and calamities with our trusted and transparent bike insurance.';

  console.log('V4 variant applied successfully');
  
  // Emit variantRendered event only after successful changes
  window.CFQ = window.CFQ || [];
  window.CFQ.push({ emit: 'variantRendered' });
} else {
  console.error('Could not find headline or subheadline elements');
  if (!headline) console.error('Headline element not found');
  if (!subheadline) console.error('Subheadline element not found');
}


//Production Code 

/*! Code generated by Coframe AI Editor */
(()=>{var t=Symbol.for("JSX.Fragment");var e=document.querySelector(".t_heading.t_heading_primary"),n=document.querySelector(".page-heading_subTitle___1u4b");e&&n?(e.textContent="Less 'What If,' More 'Let's Go!'",n.textContent="Secure your ride against accidents, theft, and calamities with our trusted and transparent bike insurance.",window.CFQ=window.CFQ||[],window.CFQ.push({emit:"variantRendered"})):(console.error("Could not find headline or subheadline elements"),e||console.error("Headline element not found"),n||console.error("Subheadline element not found"));})();
