//Session URL: https://mark-1.coframe.com/?session_id=f0b364d7-0951-4420-b65a-ed22d4bcc9ec


// Find and update radio option labels with emotionally resonant text
const radioLabels = document.querySelectorAll('.rd-sqr__txt');

if (radioLabels.length >= 2) {
  // Update "Myself" → "I want protection and independence"
  if (radioLabels[0].textContent.trim() === 'Myself') {
    radioLabels[0].textContent = 'I want protection and independence';
  }
  
  // Update "Someone else" → "I want to keep my family member safe"
  if (radioLabels[1].textContent.trim() === 'Someone else') {
    radioLabels[1].textContent = 'I want to keep my family member safe';
  }
  
  console.log('Updated radio option labels with emotionally resonant text');
  
  // Emit variant rendered event after successful update
  window.CFQ = window.CFQ || [];
  window.CFQ.push({ emit: 'variantRendered' });
} else {
  console.error('Radio option labels not found or insufficient options');
}



// Production Code

/*! Code generated by Coframe AI Editor */
(()=>{var e=Symbol.for("JSX.Fragment");var n=document.querySelectorAll(".rd-sqr__txt");n.length>=2?(n[0].textContent.trim()==="Myself"&&(n[0].textContent="I want protection and independence"),n[1].textContent.trim()==="Someone else"&&(n[1].textContent="I want to keep my family member safe"),window.CFQ=window.CFQ||[],window.CFQ.push({emit:"variantRendered"})):console.error("Radio option labels not found or insufficient options");})();
