console.log('Applying V1 - Punchier Headlines Variant');

// Find and update the main headline (h2)
const headline = document.querySelector('.t_heading.t_heading_primary');

// Find and update the subheadline (h3)
const subheadline = document.querySelector('.page-heading_subTitle___1u4b');

if (headline && subheadline) {
  // V1 Copy
  headline.textContent = 'Overtake Worry, Not Your Budget.';
  subheadline.textContent = 'Get complete on-road protection with our comprehensive and affordable two-wheeler insurance plans.';

  console.log('V1 variant applied successfully');
  
  // Emit variantRendered event only after successful changes
  window.CFQ = window.CFQ || [];
  window.CFQ.push({ emit: 'variantRendered' });
} else {
  console.error('Could not find headline or subheadline elements');
  if (!headline) console.error('Headline element not found');
  if (!subheadline) console.error('Subheadline element not found');
}



// Prodcution Code 

/*! Code generated by Coframe AI Editor */
(()=>{var t=Symbol.for("JSX.Fragment");var e=document.querySelector(".t_heading.t_heading_primary"),n=document.querySelector(".page-heading_subTitle___1u4b");e&&n?(e.textContent="Overtake Worry, Not Your Budget.",n.textContent="Get complete on-road protection with our comprehensive and affordable two-wheeler insurance plans.",window.CFQ=window.CFQ||[],window.CFQ.push({emit:"variantRendered"})):(console.error("Could not find headline or subheadline elements"),e||console.error("Headline element not found"),n||console.error("Subheadline element not found"));})();
