// CHANGEME: Hero Value Proposition - Benefit-Focused Copy Test
// Tests emotional benefit-driven headline vs. feature-focused
// Goal: Improve CVR through benefit-focused messaging

console.log('Testing benefit-focused hero headline...');

// Find the main hero H1 headline
const heroH1 = document.querySelector('h1.start-hero-title');

if (heroH1) {
    // Store original for reference
    const originalText = heroH1.textContent;
    console.log('Original headline:', originalText);

    // Update to benefit-focused copy
    heroH1.textContent = 'Watch Your Favorite Anime Ad-Free, Hours After Japan Release';

    console.log('Variant applied successfully');

    // Emit success after all changes applied
    window.CFQ = window.CFQ || [];
    window.CFQ.push({ emit: 'variantRendered' });
} else {
    console.error('Hero H1 element not found');
}









// Production ready code 


/*! Code generated by Coframe AI Editor */
(() => { var t = Symbol.for("JSX.Fragment"); var e = document.querySelector("h1.start-hero-title"); if (e) { let n = e.textContent; e.textContent = "Watch Your Favorite Anime Ad-Free, Hours After Japan Release", window.CFQ = window.CFQ || [], window.CFQ.push({ emit: "variantRendered" }) } else console.error("Hero H1 element not found"); })();
