console.log('Applying V3 - Punchier Headlines Variant');

// Find and update the main headline (h2)
const headline = document.querySelector('.t_heading.t_heading_primary');

// Find and update the subheadline (h3)
const subheadline = document.querySelector('.page-heading_subTitle___1u4b');

if (headline && subheadline) {
  // V3 Copy
  headline.textContent = 'Your Bike\'s Official Best Friend.';
  subheadline.textContent = 'With our quick claim settlements and extensive network of cashless garages, your two-wheeler is always in safe hands.';

  console.log('V3 variant applied successfully');
  
  // Emit variantRendered event only after successful changes
  window.CFQ = window.CFQ || [];
  window.CFQ.push({ emit: 'variantRendered' });
} else {
  console.error('Could not find headline or subheadline elements');
  if (!headline) console.error('Headline element not found');
  if (!subheadline) console.error('Subheadline element not found');
}



//Production Code 

/*! Code generated by Coframe AI Editor */
(()=>{var t=Symbol.for("JSX.Fragment");var e=document.querySelector(".t_heading.t_heading_primary"),n=document.querySelector(".page-heading_subTitle___1u4b");e&&n?(e.textContent="Your Bike's Official Best Friend.",n.textContent="With our quick claim settlements and extensive network of cashless garages, your two-wheeler is always in safe hands.",window.CFQ=window.CFQ||[],window.CFQ.push({emit:"variantRendered"})):(console.error("Could not find headline or subheadline elements"),e||console.error("Headline element not found"),n||console.error("Subheadline element not found"));})();
